#!/bin/bash
# variables need to be defined firstly, otherwise would run failed (if defined in the bsub workflow).

outdir=/scratch/2025-04-04/bio-shenw/Ljniu/yanke/K562_taq/mapping
rawdata_dir=/scratch/2025-04-04/bio-shenw/Ljniu/yanke/K562_taq/data
genome_bowtie2_index=/scratch/2025-04-04/bio-shenw/ref/Human/hg38/bowtie2_index_bylxx/hg38.fa

cd $outdir
for sample in ${rawdata_dir}/*_1.fq.gz;do
	sample=$(basename $sample _1.fq.gz)
	R1=$rawdata_dir/${sample}_1.fq.gz
	R2=$rawdata_dir/${sample}_2.fq.gz
	cleanR1=${outdir}/cleandata/${sample}.clean_1P.fastq.gz
	cleanR2=${outdir}/cleandata/${sample}.clean_2P.fastq.gz

	if [ ! -d $outdir/bam2 ];then
		mkdir -p ${outdir}/bam2
	fi
	bamdir=${outdir}/bam2

	bsub -J chipseq -q ser -n 20 -R "span[ptile=20]" -o ${sample}_1.log -e ${sample}_1.err <<EOF
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample processing ... "

# 1. do qc for raw data (raw data refers to cleandata generated by sequencing).
 	if [ ! -d $outdir/fastqc/qc1 ];then
 		mkdir -p $outdir/fastqc/qc1
 	fi

 	fastqc -t 20 -o $outdir/fastqc/qc1 $R1
 	fastqc -t 20 -o $outdir/fastqc/qc1 $R2
 	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample fastqc raw reads ..."

# 2. trim to remove low-quality sequences.
	if [ ! -d $outdir/cleandata ];then
		mkdir -p $outdir/cleandata
	fi

    trimmomatic PE -phred33 \
        -threads 20 $R1 $R2 \
        -baseout $outdir/cleandata/${sample}.clean.fastq.gz \
        ILLUMINACLIP:/work/bio-shenw/tools/Trimmomatic-0.39/adapters/TruSeq3-PE.fa:2:30:10 \
                        HEADCROP:15 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:90
	wait
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample Trimming ..."

## 3. do qc align to check quality.

	if [ ! -d $outdir/fastqc/qc2 ];then
		mkdir -p $outdir/fastqc/qc2
	fi

	fastqc -t 20 -o $outdir/fastqc/qc2 ${cleanR1}
	fastqc -t 20 -o $outdir/fastqc/qc2 ${cleanR2}
	wait
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample fastqc clean reads ..."

## 4. align the reads to the reference.

	bowtie2  -p 20 --no-unal -x $genome_bowtie2_index -1 $cleanR1 -2 $cleanR2 -S ${bamdir}/${sample}.sam 
	wait
	samtools sort -O bam -@ 20 -o ${bamdir}/${sample}.sorted.bam ${bamdir}/${sample}.sam
	wait
	samtools view -h -@ 20 -q 20 -b ${bamdir}/${sample}.sorted.bam >${bamdir}/${sample}.sorted.q20.bam
	rm ${bamdir}/${sample}.sam 
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample aligning ..."

## 5. remove PCR duplicates and convert bam to bw format.
	picard MarkDuplicates INPUT=${bamdir}/${sample}.sorted.q20.bam OUTPUT=${bamdir}/${sample}.sorted.q20.rmdup.bam \
				METRICS_FILE=${bamdir}/${sample}.sorted.q20.rmdup.metrics VALIDATION_STRINGENCY=LENIENT \
				REMOVE_DUPLICATES=TRUE MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000

	samtools index ${bamdir}/${sample}.sorted.bam
	samtools index ${bamdir}/${sample}.sorted.q20.bam
	samtools index ${bamdir}/${sample}.sorted.q20.rmdup.bam

	# BPM = Bins Per Million mapped reads, same as TPM in RNA-seq.
	# BPM (per bin) = number of reads per bin / sum of all reads per bin (in millions)
	#/work/bio-tanyj/miniconda3/bin/bamCoverage -b ${bamdir}/${sample}.sorted.q20.rmdup.bam -o ${bamdir}/${sample}.BPM.bw -p 20 --binSize 10 --extendReads --minMappingQuality 20 --ignoreDuplicates --normalizeUsing BPM
	/work/bio-tanyj/miniconda3/bin/bamCoverage -b ${bamdir}/${sample}.sorted.q20.rmdup.bam -o ${bamdir}/${sample}_RPKM_10bp.bw -p 10 --binSize 10 --extendReads --minMappingQuality 20 --ignoreDuplicates --normalizeUsing RPKM
    macs2 callpeak -t ${bamdir}/${sample}.sorted.q20.rmdup.bam  -f BAM -g hs -n ${sample}_q0.05 -q 0.05 -B 
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample Generating bw tracks ..."
EOF
done
