#!/bin/bash
# variables need to be defined firstly, otherwise would run failed (if defined in the bsub workflow).

outdir=/scratch/2025-09-01/bio-shenw/Cardiovascular_disease_STARR-seq/workspace_tanyj_pipeline/workspace_nonrisk/mapping
rawdata_dir=/scratch/2025-09-01/bio-shenw/Cardiovascular_disease_STARR-seq/workspace_tanyj_pipeline/data/nonrisk
genome_bowtie_index=/scratch/2025-09-01/bio-shenw/Cardiovascular_disease_STARR-seq/workspace_tanyj_pipeline/ref/CAD_risk_allel/genome/Paternal/bowtie_index/hg38_nonrisk

cd $outdir
for sample in ${rawdata_dir}/*_R1_nonrisk.fastq.gz;do
	sample=$(basename $sample _R1_nonrisk.fastq.gz)
	R1=$rawdata_dir/${sample}_R1_nonrisk.fastq.gz
	R2=$rawdata_dir/${sample}_R3_nonrisk.fastq.gz
	cleanR1=${outdir}/cleandata/${sample}_R1_nonrisk_trim100bp.fastq.gz
	cleanR2=${outdir}/cleandata/${sample}_R2_nonrisk_trim100bp.fastq.gz

	if [ ! -d $outdir/bam2 ];then
		mkdir -p ${outdir}/bam2
	fi
	bamdir=${outdir}/bam2

	bsub -J bowtie -q ser -n 20 -R "span[ptile=20]" -o ${sample}.log -e ${sample}.err <<EOF
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample processing ... "

# 1. do qc for raw data (raw data refers to cleandata generated by sequencing).
 	if [ ! -d $outdir/fastqc/qc1 ];then
 		mkdir -p $outdir/fastqc/qc1
 	fi

 	fastqc -t 20 -o $outdir/fastqc/qc1 $R1
 	fastqc -t 20 -o $outdir/fastqc/qc1 $R2
 	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample fastqc raw reads ..."

# 2. trim to remove low-quality sequences.
	if [ ! -d $outdir/cleandata ];then
		mkdir -p $outdir/cleandata
	fi

    seqtk trimfq -b 25 -e 25 ${R1} | gzip > ${cleanR1}
    seqtk trimfq -b 25 -e 25 ${R2} | gzip > ${cleanR2}


	wait
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample Trimming ..."

## 3. do qc align to check quality.

	if [ ! -d $outdir/fastqc/qc2 ];then
		mkdir -p $outdir/fastqc/qc2
	fi

	fastqc -t 20 -o $outdir/fastqc/qc2 ${cleanR1}
	fastqc -t 20 -o $outdir/fastqc/qc2 ${cleanR2}
	wait
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample fastqc clean reads ..."

## 4. align the reads to the reference.

	bowtie -p 20 -X 2000 -v 3 -m 1 --best --strata --quiet --sam -x ${genome_bowtie_index} -1 ${cleanR1} -2 ${cleanR2} -S | samtools view -@ 20 -Sb -o ${bamdir}/${sample}.bam
	wait
	samtools sort -O bam -n -@ 20 -o ${bamdir}/${sample}.sorted_n.bam ${bamdir}/${sample}.bam
	wait
	samtools fixmate ${bamdir}/${sample}.sorted_n.bam ${bamdir}/${sample}_fixmate.bam
    samtools sort -O bam -@ 20 -o ${bamdir}/${sample}_fixmate_sorted.bam ${bamdir}/${sample}_fixmate.bam
    samtools index ${bamdir}/${sample}_fixmate_sorted.bam

	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample aligning ..."


##  5. bam to bed (Illumina read ID: @<instrument>:<run number>:<flowcell ID>:<lane>:<tile>:<x-pos>:<y-pos>  <read>:<is filtered>:<control number>:<index>); 
     # only keep <tile>:<x-pos>:<y-pos> of the read ID
     # columns in output: 1. chr, 2. start(read1), 3.end(read2), 4.trimmed readID (shared by R1,R2, and UMI), 5. strand (read1)
    bedtools bamtobed -i ${bamdir}/${sample}_fixmate.bam -mate1 -bedpe | awk '{if(\$1==\$4&&\$1!="."&&\$2!=0&&\$5!=0){if(\$2>=\$5&&\$9=="-"&&\$10=="+"){start=\$5;end=\$3;strand="-"}else if(\$2<\$5&&\$9=="+"&&\$10=="-"){start=\$2;end=\$6;strand="+"};sub("^[^:]+:[^:]+:[^:]+:[^:]+:", "", \$7);print \$1, start, end, \$7, strand}}' OFS='\t'  > ${bamdir}/${sample}.bedpe 
    # the second awd seen not needed!
    

##  6. add UMI to bed (only need one CPU, but ~ 140GB/155GB RAM!)
    # UMItab: tsv file contain two columns: seqID, UMIseq.
    cat ${bamdir}/${sample}.bedpe | awk -v UMItab=$outdir/UMItab/${sample}.UMItab -v ID=${sample} -v OFS='\t' 'BEGIN{while(getline<UMItab){vec[\$1]=\$2}}{if(\$4 in vec){print \$1, \$2, \$3, \$5, \$4, vec[\$4] > ID"_UMI.bed"}else{print \$0 > ID"_noUMI.bed"}}'


	
    #/work/bio-tanyj/miniconda3/bin/bamCoverage -b ${bamdir}/${sample}_fixmate_sorted.bam -o ${bamdir}/${sample}_RPKM_10bp.bw -p 20 --binSize 10 -e 0 --minMappingQuality 20 --normalizeUsing RPKM
    #/work/bio-tanyj/miniconda3/bin/bamCoverage -b ${bamdir}/${sample}_fixmate_sorted.bam -o ${bamdir}/${sample}_10bp.bw -p 20 --binSize 10 -e 0 --minMappingQuality 20 

    #macs2 callpeak -t ${bamdir}/${sample}.sorted.q20.rmdup.bam  -f BAM -g hs -n ${sample}_q0.05 -q 0.05 -B 
	echo -e "$(date '+%Y-%m-%d %H:%M:%S') $sample Generating bw tracks ..."
EOF
done
